// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwCgZdylnZBJ7lrtd-Ug-AbAGk6_pnypw',
    appId: '1:258488420384:web:101676b080245b792bd445',
    messagingSenderId: '258488420384',
    projectId: 'rigoula-smart',
    authDomain: 'rigoula-smart.firebaseapp.com',
    storageBucket: 'rigoula-smart.firebasestorage.app',
    databaseURL: 'https://rigoula-smart-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClFDTbGa9WpC3cC3RmZk3QZGn3KYgobqM',
    appId: '1:258488420384:android:9afa41cbff333a372bd445',
    messagingSenderId: '258488420384',
    projectId: 'rigoula-smart',
    storageBucket: 'rigoula-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItVNMWupxaBGtqVnzN3Zk37_BGndAvCI',
    appId: '1:258488420384:ios:7539049c2cef07cb2bd445',
    messagingSenderId: '258488420384',
    projectId: 'rigoula-smart',
    storageBucket: 'rigoula-smart.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDItVNMWupxaBGtqVnzN3Zk37_BGndAvCI',
    appId: '1:258488420384:ios:7539049c2cef07cb2bd445',
    messagingSenderId: '258488420384',
    projectId: 'rigoula-smart',
    storageBucket: 'rigoula-smart.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwCgZdylnZBJ7lrtd-Ug-AbAGk6_pnypw',
    appId: '1:258488420384:web:3c4257d732cfbe1c2bd445',
    messagingSenderId: '258488420384',
    projectId: 'rigoula-smart',
    authDomain: 'rigoula-smart.firebaseapp.com',
    storageBucket: 'rigoula-smart.firebasestorage.app',
  );
}
